### ISSUE TITLE
Save network state by using https://capacitorjs.com/docs/apis/network

### ISSUE THREAD

**Issue by FreePhoenix888** [deep-foundation/sdk#11]
- [ ] When offline - save a network state to the capacitor storage
- [ ] When online
  - [ ] Save not saved data from capacitor storage
  - [ ] Save a network state to the capacitor storage

Deep types for every [connection type](https://capacitorjs.com/docs/apis/network#connectiontype) must be created and used

https://capacitorjs.com/docs/apis/network

**Comment by Romanxz** [comment]
### .env
```
NEXT_PUBLIC_GQL_PATH=<gql-client-path>/gql     
NEXT_PUBLIC_GQL_SSL=0/1 for local/remote
```
### Make sure to use nodejs version 14.15.0

```bash
npm ci
```
```bash
npm run dev -- -p 4000
```

## Use


![Image](https://user-images.githubusercontent.com/44348954/220389617-cb6e4a36-0d23-4728-aa2b-981048c37bd4.png)

### 1) INITIALIZE PACKAGE. 

Also creates Network container link inside current device link.

### 2) LISTEN TO NETWORK CHANGES. 

Fires capacitor/network Network event listener. Listens to network changes. 

Stores them as string values inside localstore. Uploads as links values inside Network link container if possible.

"none" - airplane mode

"wifi" - wifi

"cellular" - mobile network

"unknown" -actually unknown for me, cant figure out what to do to emit this event.

You can emit events by turning these connection types on and off inside settings overlay on your phone.

A good idea would be connecting your phone to android studio by usb cable and wrap it with aluminium foil to simulate network loss and still be able to watch debug logs where this event can be seen clearly.

### 3) SAVE CURRENT STATUS. 

Saves current network type and status as link value.
