### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by CEHR2005** [deep-foundation/sdk#2]
### Is your feature request related to a problem? Please describe.

Add description to README.md

### Describe the solution you'd like

Update README.md

**Comment by FreePhoenix888** [comment]
What is this?

**Comment by FreePhoenix888** [comment]
I do not understand what has to be done

**Comment by FreePhoenix888** [comment]
Fixed in https://github.com/deep-foundation/sdk/commit/9d0ab24cba0c7e56fcb2a76e50ca14d3378d0ae6
